#! /bin/sh

#Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
picom --experimental-backends &
#nitrogen --restore &
feh --bg-fill $HOME/Pictures/sunset5.jpg &
$HOME/.config/polybar/launch.sh

#Workspaces
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          16
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

